<a href="https://colab.research.google.com/github/Joeaviator/RECOMMENDATION_ENGINE/blob/main/Recommendation_Engine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from google.colab import files
file=files.upload()

Saving ratings.csv to ratings (1).csv
Saving movies.csv to movies (1).csv

In [20]:
import pandas as pd

In [21]:
#Load datasets
movies_ds=pd.read_csv("movies.csv")
rating_ds=pd.read_csv("ratings.csv")

In [22]:
#Read the datasets
movies_ds.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [23]:
rating_ds.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [24]:
movies_ds['title'] = movies_ds['title'].str.replace(r'\s*\(\d{4}\)', '', regex=True)
movies_ds['title'] = movies_ds['title'].str.replace(r'\s*\(\)\s*', '', regex=True).str.strip()

In [25]:
movies_ds.head()

,movieId,title,genres
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji,Adventure|Children|Fantasy
2,3,Grumpier Old Men,Comedy|Romance
3,4,Waiting to Exhale,Comedy|Drama|Romance
4,5,Father of the Bride Part II,Comedy

In [26]:
#remove | this from genres
movies_ds['genres']=movies_ds['genres'].str.split('|')
movies_ds.head()

,movieId,title,genres
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Jumanji,"[Adventure, Children, Fantasy]"
2,3,Grumpier Old Men,"[Comedy, Romance]"
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]"
4,5,Father of the Bride Part II,[Comedy]

In [27]:
rating_ds.drop('timestamp',axis=1,inplace=True)
rating_ds.head()

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [28]:
#One hot encoding-convert categories into numbers
movies_copy=movies_ds.copy()
for i,row in movies_ds.iterrows():
  for genre in row['genres']:
    movies_copy.at[i,genre]=1
#replace the null values in movies copy
movies_copy=movies_copy.fillna(0)

In [29]:
movies_copy.head()

,movieId,title,genres,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,...,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men,"[Comedy, Romance]",0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",0.0,0.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II,[Comedy],0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
user_input=[""]
for i in range(3):
  name=input("Enter Movie Name:")
  rating=float(input("Enter Rating:"))
  user_input.append({"title":name,"rating":rating})
#convert into a list to have a structured format
uder_df=pd.DataFrame(user_input)

Enter Movie Name:Toy story
Enter Rating:4.3
Enter Movie Name:Top Gun
Enter Rating:4.7
Enter Movie Name:Ethan Hunt
Enter Rating:4.8